# Generated by Django 2.2.1 on 2019-08-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instances',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='instances',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
    ]
