# Generated by Django 2.2.1 on 2019-08-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(db_index=True, help_text='service名称', max_length=32, verbose_name='节点名称')),
                ('pid', models.IntegerField(db_index=True, help_text='pid', verbose_name='节点pid')),
                ('path_node', models.CharField(db_index=True, help_text='node中文path', max_length=32, verbose_name='节点中文path')),
                ('groups', models.ManyToManyField(help_text='用户组关联节点', related_name='node_group', to='auth.Group', verbose_name='用户组关联节点')),
            ],
            options={
                'db_table': 'pms_node',
                'ordering': ['id'],
            },
        ),
    ]
