# Generated by Django 2.2.1 on 2019-08-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicetree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='op',
            field=models.CharField(help_text='运维负责人', max_length=255, null=True, verbose_name='运维负责人'),
        ),
        migrations.AlterField(
            model_name='node',
            name='rd',
            field=models.CharField(help_text='业务负责人', max_length=255, null=True, verbose_name='业务负责人'),
        ),
    ]
