# Generated by Django 2.2.1 on 2019-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='app',
            field=models.CharField(help_text='APP名称', max_length=64, verbose_name='APP名称'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(help_text='权限简称', max_length=64, verbose_name='权限简称'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='desc',
            field=models.CharField(help_text='权限描述信息', max_length=64, verbose_name='权限描述信息'),
        ),
    ]
